name: brad hawkins
favicon: null
layout_spectrum: 0
typography_spectrum: 0.85229
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#87985f'
    - '#8bbddd'
    - '#305471'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
