layout_spectrum: 0.346543
typography_spectrum: 0.851602
color:
  saturation: 0.8853288
  lightness: 0.6129848
  brandStrength: 0.4890388
  rhythmicContrast: 0.8600338
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Brad hawkins
